#signalmanager.gd (global)
extends Node3D

@warning_ignore("unused_signal")
signal set_spawn_marker(spawner: Marker3D)
@warning_ignore("unused_signal")
signal set_theke_marker(theke: Marker3D)
@warning_ignore("unused_signal")
signal set_look_at_marker(look_at: Marker3D)
@warning_ignore("unused_signal")
signal set_customer_exit(exit: Marker3D)
@warning_ignore("unused_signal")
signal update_money(amount: int)
@warning_ignore("unused_signal")
signal switch_menuBtn_visibility(value: bool)
@warning_ignore("unused_signal")
signal on_resume()
@warning_ignore("unused_signal")
signal open_shop()
@warning_ignore("unused_signal")
signal update_time_left(time: float)

@warning_ignore("unused_signal")
signal customer_leaves_front()
